<?php

namespace ItechSup\ItechSisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClosingDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClosingDayRepository extends EntityRepository
{
}
